name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: echo "Setting up environment..."

      - name: Run my action
        id: my-action
        uses: my-org/my-action@v1
        with:
          input-param: ${{ secrets.MY_SECRET }}
          output-file: my-output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: my-output.txt

